language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nbarr/udemy-kubernetes-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true nbarr/udemy-kubernetes-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "udemy-kubernetes-docker"
  env: "UdemyKubernetesDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-033874350870"
  bucket_path: "udemy-kubernetes-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
